import random as random

def summon():
    reports = [
        "@everyone **AND I SAW THE SEVEN ANGELS WHICH STOOD BEFORE GOD; AND TO THEM WERE GIVEN SEVEN TRUMPETS. AND ANOTHER ANGEL CAME AND STOOD AT THE ALTAR, HAVING A GOLDEN CENSER; AND THERE WAS GIVEN UNTO HIM MUCH INCENSE, THAT HE SHOULD OFFER IT WITH THE PRAYERS OF ALL SAINTS UPON THE GOLDEN ALTAR WHICH WAS BEFORE THE THRONE. AND THE SMOKE OF THE INCENSE, WHICH CAME WITH THE PRAYERS OF THE SAINTS, ASCENDED UP BEFORE GOD OUT OF THE ANGEL'S HAND. AND THE ANGEL TOOK THE CENSER, AND FILLED IT WITH FIRE OF THE ALTAR, AND CAST IT INTO THE EARTH: AND THERE WERE VOICES, AND THUNDERINGS, AND LIGHTNINGS, AND AN EARTHQUAKE. AND THE SEVEN ANGELS WHICH HAD THE SEVEN TRUMPETS PREPARED THEMSELVES TO SOUND: *IT IS TIME FOR PRACTICE.***",
        
        "@everyone Let us go then, you and I,\nWhen the evening is spread out against the sky\nLike a patient etherized upon a table;\nLet us go, through certain half-deserted streets,\nThe muttering retreats\nOf restless nights in one-night cheap hotels\nAnd sawdust restaurants with oyster-shells:\nStreets that follow like a tedious argument\nOf insidious intent\nTo lead you to an overwhelming question ...\nOh, do not ask, “What is it?”\nBecause it's obviously time for Quiz Bowl practice, ya dingus.",
        
        "Naea Michael Jackson is a Niuean journalist and former politician.\nIn the 1970s and 1980s, he was government printer and government press photographer in Niue. He published the Tohi Tala Niue, Niue's government-owned weekly newspaper. In 1991, he set up a private printing business, and, in 1993, launched the weekly Niue Star, which at the time was the country's only printed newspaper. Jackson is the Star's owner, editor, journalist and photographer.\nAlso in 1993, Jackson stood successfully for Parliament in that year's general election. He later became an associate minister, and remained a member of Parliament until 2008, when he was defeated in the general election. He stated that there was \"no conflict of interest\" between his being a journalist and a member of government, because \"we have a law to prevent us MPs from taking advantage of our positions\".\nHe is reportedly better known in Niue than his internationally more famous namesake, to the point that, when news of singer Michael Jackson's death reached Niue in July 2009, \"most residents of the remote coral atoll (sic) thought that it was him (sic) who had died\".\nUh anyway it's time for Quiz Bowl practice @everyone",
        
        "The car's on fire, and there's no driver at the wheel/And the sewers are all muddied with a thousand lonely suicides/And a dark wind blows\nThe government is corrupt/And we're on so many drugs/With the radio on and the curtains drawn\nWe're trapped in the belly of this horrible machine/And the machine is bleeding to death\nThe sun has fallen down/And the billboards are all leering/And the flags are all dead at the top of their poles\nIt went like this:\nThe buildings toppled in on themselves/Mothers clutching babies/Picked through the rubble/And pulled out their hair\nThe skyline was beautiful on fire/All twisted metal stretching upwards/Everything washed in a thin orange haze\nI said, \"Kiss me, you're beautiful -/These are truly the last days\"\nYou grabbed my hand/And we fell into it/Like a daydream/Or a fever\nWe woke up one morning and fell a little further down/For sure it's the valley of death\nI open up my wallet/And it's full of blood\nAnyway, it's time for practice @everyone",
        
        "Open here I flung the shutter, when, with many a flirt and flutter,\nIn there stepped a stately Raven of the saintly days of yore;\nNot the least obeisance made he; not a minute stopped or stayed he;\nBut, with mien of lord or lady, perched above my chamber door—\nPerched upon a bust of Pallas just above my chamber door—\nPerched, and sat, and nothing more.\n\nThen this ebony bird beguiling my sad fancy into smiling,\nBy the grave and stern decorum of the countenance it wore,\n“Though thy crest be shorn and shaven, thou,” I said, “art sure no craven,\nGhastly grim and ancient Raven wandering from the Nightly shore—\nTell me what thy lordly name is on the Night’s Plutonian shore!”\nQuoth the Raven “@everyone It is time for practice.”",
        
        "The sea is calm tonight.\nThe tide is full, the moon lies fair\nUpon the straits; on the French coast the light\nGleams and is gone; the cliffs of England stand,\nGlimmering and vast, out in the tranquil bay.\nCome to the window, sweet is the night-air!\nOnly, from the long line of spray\nWhere the sea meets the moon-blanched land,\nListen! you hear the grating roar\nOf pebbles which the waves draw back, and fling,\nAt their return, up the high strand,\nBegin, and cease, and then again begin,\nWith tremulous cadence slow, and bring\nThe eternal note of practice in.\nBecause @everyone it's time for practice.",
        
        "So there stood Matthew Arnold and this girl\nWith the cliffs of England crumbling away behind them,\nAnd he said to her, \"Try to be true to me,\nAnd I'll do the same for you, for things are bad\nAll over, but you should definitely take the time to go to Quiz Bowl practice\nIn fact, @everyone should probably come to practice right now.\"",
        
        "Rise like Lions after slumber\nIn unvanquishable number,\nShake your chains to earth like dew\nWhich in sleep had fallen on you --\nYe are many -- they are few.\nAnd @everyone it's time for Quiz Bowl practice, too.",
        
        "He saw three high-seats, each above the other, and three men sat thereon,-one on each. And he asked what might be the name of those lords. He who had conducted him in answered that the one who sat on the nethermost high-seat was a king, \"and his name is High but the next is named Just-as-High; and he who is uppermost is called Third.\" Then Hárr asked the newcomer whether his errand were more than for the meat and drink which were always at his command, as for every one there in the Hall of the High One. He answered that he first desired to learn whether there were any wise man there within. Hárr said, that he should not escape whole from thence unless he were wiser, and to prove it he should go to Quiz Bowl practice. In fact, @everyone should come to practice.",
        
        "I'm the man who walked the water and tied the whale's tail in a knot\nTaught the little fishes how to swim\nCrossed the burning sands and shook the devil's hand\nRode round the world on the back of a snail carrying a sack saying AIR MAIL.\nWalked 49 miles of barbwire and used a Cobra snake for a necktie\nI'm the only man in the world who knows why white milk makes yellow butter.\nI know where the lights go when you cut the switch off.\nI might not be the best in the world, but I'm in the top two and my brother's getting old.\nAnd ain't nothing bad 'bout you but your breath.\n@everyone it's time for practice.",
        
        "Beneath those rugged elms, that yew-tree's shade,\nWhere heaves the turf in many a mould'ring heap,\nEach in his narrow cell for ever laid,\nThe rude forefathers of the hamlet sleep.\n\nThe breezy call of incense-breathing Morn,\nThe swallow twitt'ring from the straw-built shed,\nThe cock's shrill clarion, or the echoing horn,\nNo more shall rouse them from their lowly bed.\nBut pinging them should work.\n@everyone it's time for practice.",
        
        "Sol thro' white curtains shot a tim'rous ray,\nAnd op'd those eyes that must eclipse the day;\nNow lap-dogs give themselves the rousing shake,\nAnd sleepless lovers, just at twelve, awake:\nThrice rung the bell, the slipper knock'd the ground,\nAnd the press'd watch return'd a silver sound.\nThe sound of being ping'd, for @everyone 'tis time for practice.",
        
        "Friends, Romans, countrymen, lend me your ears;\nI come to ping you, not to bother you.\nThe evil that men do lives after them;\nThe good is oft interred with their bones;\nSo let it be with pinging you.\nFor @everyone it is time for practice, and you must be alerted.",
        
        "I long thought, where\nthe tiger on the street came from.\nI thought & thought,\nThought & thought\nThought & thought\nThought & thought\nAnd at that time the wind blew\nAnd I forgot what I was thinking about.\nAnd so I don't know\nwhere the tiger on the street came from.\nThat poem is Тигр на улице by Даниил Хармс, translated by Van Holthenrichs. I have no segue here. @everyone it's time for practice.",
        
        "Dearest creature in creation\nStudying English pronunciation,\nI will teach you in my verse\nSounds like corpse, corps, horse and worse.\n\nSword and sward, retain and Britain\n(Mind the latter how it's written).\nMade has not the sound of bade,\nSay-said, pay-paid, laid but plaid.\n\nDon't you think so, reader, rather,\nSaying lather, bather, father?\nFinally, which rhymes with enough,\nThough, through, bough, cough, hough, sough, tough??\n\nHiccough has the sound of sup...\nMy advice is: GIVE IT UP! Play Quiz Bowl instead. @everyone should, in fact, because it's time for practice."
        ]
    return random.choice(reports)
